/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.occb.jefe.registradores;

import java.util.Observable;
import proyecto2.logic.Funcionario;

/**
 *
 * @author Dani
 */
public class RegistradorView extends javax.swing.JInternalFrame implements java.util.Observer{
    RegistradorController controller;
    RegistradorModel model;
    public RegistradorView() {
        super("", false, true);
        initComponents();
    }

    public RegistradorController getController() {
        return controller;
    }

    public void setController(RegistradorController controller) {
        this.controller = controller;
    }

    public RegistradorModel getModel() {
        return model;
    }

    public void setModel(RegistradorModel model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        funcionariosTab = new javax.swing.JTable();

        funcionariosTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        funcionariosTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariosTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(funcionariosTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionariosTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosTabMouseClicked
        if(evt.getClickCount() ==2){
            int row = funcionariosTab.getSelectedRow();
        }
    }//GEN-LAST:event_funcionariosTabMouseClicked

  @Override
    public void update(Observable o, Object arg) {
        Funcionario filtro = model.getFilter();
        this.funcionariosTab.setModel(model.getFuncionarios());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable funcionariosTab;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
