/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.occb.secretaria.listado;

import java.util.Observable;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import proyecto2.Application;
import proyecto2.logic.Solicitud;

/**
 *
 * @author oscar
 */
public class SecretariaView extends javax.swing.JInternalFrame implements java.util.Observer{  
    /**
     * Creates new form SolicitudesView
     */
    SecretariaController controller;
    SecretariaModel model;
    
    public SecretariaView() {
        super("",false,true);
        initComponents();
    }

    public SecretariaController getController() {
        return controller;
    }

    public void setController(SecretariaController controller) {
        this.controller = controller;
    }

    public SecretariaModel getModel() {
        return model;
    }

    public void setModel(SecretariaModel model) {
        this.model = model;
        model.addObserver(this);
    }
    public void limpiarErrores(){
        this.comprobante.setForeground(Application.COLOR_OK);
    }
    
    public void fromSolicitud(Solicitud filtro){
        comprobanteFld.setText(filtro.getComprobante());
    }
    
    Solicitud toSolicitud(){
        Solicitud result=new Solicitud();
        result.setComprobante(comprobanteFld.getText());
        return result;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarButton = new javax.swing.JButton();
        comprobanteFld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        solicitudes = new javax.swing.JTable();
        aceptarButton = new javax.swing.JButton();
        rechazarButton = new javax.swing.JButton();
        comprobante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        buscarButton.setText("buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(solicitudes);

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        rechazarButton.setText("Rechazar");
        rechazarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechazarButtonActionPerformed(evt);
            }
        });

        comprobante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comprobante.setText("Comprobante:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(comprobante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comprobanteFld, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(aceptarButton)
                        .addGap(18, 18, 18)
                        .addComponent(rechazarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarButton)
                    .addComponent(comprobanteFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprobante))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(rechazarButton))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        try{
            controller.buscar(this.toSolicitud());
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_buscarButtonActionPerformed
    Solicitud seleccionada;
    private void rechazarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechazarButtonActionPerformed
        // TODO add your handling code here:
        JTextField motivo=new JTextField();
        Object[] message={"Motivo de rechazo: ",motivo};
        int Option = JOptionPane.showConfirmDialog(null, message,"Motivo",JOptionPane.OK_CANCEL_OPTION);
//        try{
//            
//            if(motivo.getText().isEmpty()){
//                JOptionPane.showMessageDialog(null, "Error, debe digitar un motivo");
//                return;
//            }
//            else {
//                seleccionada.setMotivioRechazo(motivo.getText());
//                //seleccionada.setEstado("rechazada");
//                controller.actualizar(seleccionada,"rechazada");
//            }
//        }catch(Exception e){ }

        //probando 
        try{
            if(motivo.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Error, debe digitar un motivo");
                return;
            }
        }catch(Exception e){}
        
        if(Option == JOptionPane.OK_OPTION){
            try{
                controller.actualizarMotivo(seleccionada, "rechazado", motivo.getText());
            }catch(Exception e){}
        }
        
        
    }//GEN-LAST:event_rechazarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        try{
            controller.actualizar(seleccionada,"por verificar");
        }catch(Exception e){}
    }//GEN-LAST:event_aceptarButtonActionPerformed
   
    private void solicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitudesMouseClicked
        // TODO add your handling code here:
        try{
            int row=solicitudes.getSelectedRow();
            seleccionada= model.getSolicitudes().getRowAt(row);
            
        }catch(Exception e){
        }
    }//GEN-LAST:event_solicitudesMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel comprobante;
    private javax.swing.JTextField comprobanteFld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rechazarButton;
    private javax.swing.JTable solicitudes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        this.limpiarErrores();
        Solicitud filtro=model.getFilter();
        this.fromSolicitud(filtro);
        solicitudes.setModel(model.getSolicitudes());
    }
}
