/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.solicitudes.edicion;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto2.Application;
import proyecto2.logic.Bien;
import proyecto2.logic.Dependencia;
import proyecto2.logic.Labor;
import proyecto2.logic.Solicitud;

/**
 *
 * @author Rodrigo Meléndez
 */
public class SolicitudView extends javax.swing.JInternalFrame implements java.util.Observer {
    SolicitudModel model;
    SolicitudController controller;

    public SolicitudModel getModel() {
        return model;
    }

    public void setModel(SolicitudModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public SolicitudController getController() {
        return controller;
    }

    public void setController(SolicitudController controller) {
        this.controller = controller;
    }
    /**
     * Creates new form solicitud2
     */
    public SolicitudView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_Fecha = new javax.swing.JLabel();
        text_Fecha = new javax.swing.JTextField();
        label_Tipo = new javax.swing.JLabel();
        comboBox_Tipo = new javax.swing.JComboBox<>();
        label_Comprobante = new javax.swing.JLabel();
        text_Comprobante = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Bien = new javax.swing.JTable();
        button_AgregaBien = new javax.swing.JButton();
        button_EliminaBien = new javax.swing.JButton();
        text_Descripcion = new javax.swing.JTextField();
        text_Marca = new javax.swing.JTextField();
        text_Cantidad = new javax.swing.JTextField();
        text_Precio = new javax.swing.JTextField();
        label_Descripcion = new javax.swing.JLabel();
        label_Marca = new javax.swing.JLabel();
        label_Modelo = new javax.swing.JLabel();
        label_Cantidad = new javax.swing.JLabel();
        label_Precio = new javax.swing.JLabel();
        text_Modelo = new javax.swing.JTextField();
        button_Guardar = new javax.swing.JButton();
        button_Salir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Solicitud"));

        label_Fecha.setText("Fecha");

        text_Fecha.setForeground(new java.awt.Color(153, 153, 153));
        text_Fecha.setText("Ej.dd/mm/yyyy");
        text_Fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_FechaMouseClicked(evt);
            }
        });

        label_Tipo.setText("Tipo");

        comboBox_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_Comprobante.setText("Comprobante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(label_Comprobante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(label_Fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(label_Tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBox_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Tipo)
                    .addComponent(text_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Fecha)
                    .addComponent(label_Comprobante)
                    .addComponent(text_Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 830, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bienes"));

        table_Bien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_Bien);

        button_AgregaBien.setText("Agregar");
        button_AgregaBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AgregaBienActionPerformed(evt);
            }
        });

        button_EliminaBien.setText("Eliminar");
        button_EliminaBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EliminaBienActionPerformed(evt);
            }
        });

        text_Cantidad.setForeground(new java.awt.Color(153, 153, 153));
        text_Cantidad.setText("0");
        text_Cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_CantidadMouseClicked(evt);
            }
        });

        text_Precio.setForeground(new java.awt.Color(153, 153, 153));
        text_Precio.setText("0.0");
        text_Precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_PrecioMouseClicked(evt);
            }
        });

        label_Descripcion.setText("Descripción");

        label_Marca.setText("Marca");

        label_Modelo.setText("Modelo");

        label_Cantidad.setText("Cantidad");

        label_Precio.setText("Precio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_Descripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_Marca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Modelo)
                            .addComponent(text_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_Cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Precio)
                            .addComponent(text_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_AgregaBien))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_EliminaBien)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Descripcion)
                    .addComponent(label_Marca)
                    .addComponent(label_Modelo)
                    .addComponent(label_Cantidad)
                    .addComponent(label_Precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_AgregaBien)
                    .addComponent(text_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_EliminaBien)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 830, 300));

        button_Guardar.setText("Guardar");
        button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(button_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        button_Salir.setText("Salir");
        button_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(button_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_EliminaBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EliminaBienActionPerformed
        try {
            int row = this.table_Bien.getSelectedRow();
            int col = this.table_Bien.getSelectedColumn();
            this.controller.borrarBien(row); //Mandar una excepcion si agrega Dependencia es null
            JOptionPane.showMessageDialog(this, "Solicitud Eliminada Exitosamente", "OK", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_EliminaBienActionPerformed

    private void button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GuardarActionPerformed
        if (this.validarSolicitud()) {
            try {
                this.controller.guardarSolicitud(this.agregaSolicitud(), codigoSolicitud); //Mandar una excepcion si agrega Dependencia es null
                JOptionPane.showMessageDialog(this, "Solicitud Agregada Exitosamente", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Datos invalidos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_GuardarActionPerformed

    private void button_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SalirActionPerformed
        this.text_Comprobante.setText("");
        this.text_Fecha.setForeground(new java.awt.Color(153,153,153));
        this.text_Fecha.setText("Ej.dd/mm/yyyy");
        this.controller.getModel().setListaBienes(new ArrayList<Bien>());
        try {
            if(this.controller.getModel().getModoS() == Application.MODO_EDITAR)
               this.controller.getModel().setModoS(Application.MODO_AGREGAR); 
            this.controller.refrescarTablaBien();
        } catch (Exception ex) {
            Logger.getLogger(SolicitudView.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.controller.hide();
    }//GEN-LAST:event_button_SalirActionPerformed

    private void button_AgregaBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AgregaBienActionPerformed
        try {
        if(this.validarBien()){
            int ident = 0;
            //this.controller.refrescarTablaBien();
            this.controller.guardarBien(this.agregaBien());
            this.text_Descripcion.setText("");
            this.text_Marca.setText("");
            this.text_Modelo.setText("");
            this.text_Cantidad.setForeground(new java.awt.Color(153,153,153));
            this.text_Precio.setForeground(new java.awt.Color(153,153,153));
            this.text_Cantidad.setText("0");
            this.text_Precio.setText("0.0");
            if(this.controller.getModel().getModoS() == Application.MODO_EDITAR){
                ident = 1;
                this.controller.getModel().setModoS(Application.MODO_AGREGAR);
            }
            this.controller.refrescarTablaBien();
            if(this.controller.getModel().getModoS() == Application.MODO_AGREGAR && ident == 1){
                ident = 0;
                this.controller.getModel().setModoS(Application.MODO_EDITAR);
            }
            //this.controller.refrescarTablaBien();
            
        }
        else
            JOptionPane.showMessageDialog(this, "Datos invalidos", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_AgregaBienActionPerformed

    private void text_CantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_CantidadMouseClicked
        this.text_Cantidad.setForeground(Color.BLACK);
        this.text_Cantidad.setText("");
    }//GEN-LAST:event_text_CantidadMouseClicked

    private void text_PrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrecioMouseClicked
        this.text_Precio.setForeground(Color.BLACK);
        this.text_Precio.setText("");
    }//GEN-LAST:event_text_PrecioMouseClicked

    private void text_FechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_FechaMouseClicked
        this.text_Fecha.setForeground(Color.BLACK);
        this.text_Fecha.setText("");
    }//GEN-LAST:event_text_FechaMouseClicked

    private boolean validarSolicitud() {
        boolean error = true;
        this.label_Comprobante.setForeground(Application.COLOR_OK);
        this.label_Fecha.setForeground(Application.COLOR_OK);
        if (this.text_Comprobante.getText().isEmpty()) {
            this.label_Comprobante.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (this.text_Fecha.getText().isEmpty()) {
            this.label_Fecha.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
        try {
            sdf.parse(this.text_Fecha.getText()); 
        } catch (ParseException ex) {
            this.label_Fecha.setForeground(Application.COLOR_ERROR);
            error = false;
            JOptionPane.showMessageDialog(this, "Mal formato de la fecha (D/M/Y)", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
//        if (!validarBien()) {
//            error = false;
//        }
        return error;
    }

    private boolean validarBien() {
        boolean error = true;
        this.label_Descripcion.setForeground(Application.COLOR_OK);
        this.label_Marca.setForeground(Application.COLOR_OK);
        this.label_Modelo.setForeground(Application.COLOR_OK);
        this.label_Cantidad.setForeground(Application.COLOR_OK);
        this.label_Precio.setForeground(Application.COLOR_OK);
        if (this.text_Descripcion.getText().isEmpty()) {
            this.label_Descripcion.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (this.text_Marca.getText().isEmpty()) {
            this.label_Marca.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (this.text_Modelo.getText().isEmpty()) {
            this.label_Modelo.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (Integer.parseInt(this.text_Cantidad.getText()) == 0 || this.text_Cantidad.getText().isEmpty()) {
            this.label_Cantidad.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (Double.parseDouble(this.text_Precio.getText()) == 0.0 || this.text_Precio.getText().isEmpty()) {
            this.label_Precio.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        return error;
    }

    Solicitud agregaSolicitud() throws ParseException {
        Solicitud s = new Solicitud();
        s.setComprobante(this.text_Comprobante.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
        try {
            s.setFecha(sdf.parse(this.text_Fecha.getText())); 
        } catch (ParseException ex) {
            this.label_Fecha.setForeground(Application.COLOR_ERROR);
            JOptionPane.showMessageDialog(this, "Mal formato de la fecha (D/M/Y)", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        s.setTipoAdquisicion((String) this.comboBox_Tipo.getSelectedItem());
        s.setEstado("Solicitud recibida");
        s.setCantidad(controller.getCantidad());
        s.setMonto(controller.getMonto());
//        s.setBiens(new HashSet<Bien>(proyecto2.logic.ModelGeneral.instance().searchBien(this.controller.model.getFilter()))); //Como agregar los bienes
        return s;
    }

    Bien agregaBien(){
        Bien b=new Bien();
        b.setDescripcion(text_Descripcion.getText());
        b.setMarca(text_Marca.getText());
        b.setModelo(text_Modelo.getText());
        b.setCantidad(Integer.parseInt(text_Cantidad.getText()));
        b.setPrecio(Double.parseDouble(text_Precio.getText()));
        return b;
    }
    
    int codigoSolicitud;
    public void modifica(Solicitud s) throws Exception {
        this.text_Comprobante.setText(s.getComprobante());
        //this.text_Fecha.setText(s.getComprobante());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        this.text_Fecha.setText(sdf.format(s.getFecha()));
        this.text_Fecha.setForeground(Color.BLACK);
        this.comboBox_Tipo.setSelectedItem(s.getTipoAdquisicion());
        if(controller.getModel().getModoS() == Application.MODO_EDITAR)
            codigoSolicitud = s.getCodigo();
        //this.controller.agregaBien2(s.getCodigo());
        controller.refrescarTablaBien();
        controller.getModel().setCurrentS(s);
    }
    
    public void fromSolicitud(Solicitud actual) { //NO SE SI FUNCIONE, TENGO DUDAS DE SU FUNCIONAMIENTO
        try {
//            this.label_Comprobante.setEnabled(model.getModoS() == Application.MODO_AGREGAR);
//            if (actual.getEstado() == "solicitud recibida") {
//                this.label_Comprobante.setEnabled(model.getModoS() == Application.MODO_EDITAR);
//            }
//            this.label_Comprobante.setText(actual.getComprobante());
            Boolean editable = Arrays.asList(Application.MODO_AGREGAR, Application.MODO_EDITAR).contains(model.getModoS());

            this.label_Fecha.setEnabled(editable);
//            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yyyy");
//            this.text_Fecha.setText(sdf.format(actual.getFecha()));
            this.comboBox_Tipo.setSelectedItem(actual.getTipoAdquisicion());
//            this.controller.refrescarTablaBien();
            this.button_Guardar.setVisible(editable);
            this.validate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    public void limpiarErrores() {
        this.label_Comprobante.setForeground(Application.COLOR_OK);
        this.label_Fecha.setForeground(Application.COLOR_OK);
    }
    
//    public Labor buscaLabor(String id){
//        return proyecto2.logic.ModelGeneral.instance().searchLabor(id);
//    }
    
    @Override
    public void update(Observable o, Object arg) {
        this.limpiarErrores();
        Solicitud actual = model.getCurrentS();
        this.fromSolicitud(actual);
        this.table_Bien.setModel(model.getBien());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_AgregaBien;
    private javax.swing.JButton button_EliminaBien;
    private javax.swing.JButton button_Guardar;
    private javax.swing.JButton button_Salir;
    private javax.swing.JComboBox<String> comboBox_Tipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Cantidad;
    private javax.swing.JLabel label_Comprobante;
    private javax.swing.JLabel label_Descripcion;
    private javax.swing.JLabel label_Fecha;
    private javax.swing.JLabel label_Marca;
    private javax.swing.JLabel label_Modelo;
    private javax.swing.JLabel label_Precio;
    private javax.swing.JLabel label_Tipo;
    private javax.swing.JTable table_Bien;
    private javax.swing.JTextField text_Cantidad;
    private javax.swing.JTextField text_Comprobante;
    private javax.swing.JTextField text_Descripcion;
    private javax.swing.JTextField text_Fecha;
    private javax.swing.JTextField text_Marca;
    private javax.swing.JTextField text_Modelo;
    private javax.swing.JTextField text_Precio;
    // End of variables declaration//GEN-END:variables

}
