package proyecto2.logic;
// Generated 30/10/2018 06:44:16 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String username;
     private Funcionario funcionario;
     private String password;

    public Usuario() {
    }

	
    public Usuario(String username, Funcionario funcionario) {
        this.username = username;
        this.funcionario = funcionario;
    }
    public Usuario(String username, Funcionario funcionario, String password) {
       this.username = username;
       this.funcionario = funcionario;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


