/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.registrador.solicitudeslistado;

import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class RegistradorView extends javax.swing.JInternalFrame implements java.util.Observer{

    /**
     * Creates new form RegistradorView
     */
    RegistradorController controller;
    RegistradorModel model;
    
    
    
    public RegistradorView() {
        super("",false,true);
        initComponents();
    }

    public RegistradorController getController() {
        return controller;
    }

    public void setController(RegistradorController controller) {
        this.controller = controller;
    }

    public RegistradorModel getModel() {
        return model;
    }

    public void setModel(RegistradorModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        solicitudes = new javax.swing.JTable();
        buscarButton = new javax.swing.JButton();
        comprobante = new javax.swing.JLabel();
        comprobanteFld = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        estadosComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(solicitudes);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        comprobante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comprobante.setText("Comprobante");

        estado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estado.setText("Estado");

        estadosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "recibido", "por verificar", "rechazado", "por rotular", "procesada" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comprobante)
                .addGap(2, 2, 2)
                .addComponent(comprobanteFld, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estadosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprobante)
                    .addComponent(comprobanteFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado)
                    .addComponent(buscarButton)
                    .addComponent(estadosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        try{
            //controller.buscar(this.estadosComboBox);
            //String selected_text = ComboBox.getItemAt(ComboBox.getSelectedIndex());
            //probando
           
            //estadosList.getSelectedItem()
           //controller.buscar(estados);
          
           String selected_text= estadosComboBox.getItemAt(estadosComboBox.getSelectedIndex());
           controller.buscar(selected_text);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_buscarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel comprobante;
    private javax.swing.JTextField comprobanteFld;
    private javax.swing.JLabel estado;
    private javax.swing.JComboBox<String> estadosComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable solicitudes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        solicitudes.setModel(model.getSolicitudes());
    }
}
