/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.activosGeneral;

import java.util.Observable;
import javax.swing.JOptionPane;
import proyecto2.logic.Activo;
import proyecto2.logic.Solicitud;
import proyecto2.presentation.administrador.listado.AdministradorSolicitudController;
import proyecto2.presentation.administrador.listado.AdministradorSolicitudModel;

/**
 *
 * @author Rodrigo Meléndez
 */
public class ActivoGeneralView extends javax.swing.JInternalFrame implements java.util.Observer{

    ActivoGeneralController controller;
    ActivoGeneralModel model;
    
    /**
     * Creates new form ActivoGeneralView
     */
    public ActivoGeneralView() {
        initComponents();
    }
    
    public ActivoGeneralController getController() {
        return controller;
    }

    public void setController(ActivoGeneralController controller) {
        this.controller = controller;
    }

    public ActivoGeneralModel getModel() {
        return model;
    }

    public void setModel(ActivoGeneralModel model) {
        this.model = model;
         model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_Busca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Activo = new javax.swing.JTable();
        box_clasificacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(text_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 197, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        table_Activo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_Activo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 578, 120));

        box_clasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Categoría", "Descripción", "Dependencia", "Responsable" }));
        getContentPane().add(box_clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel1.setText("Búsqueda mediante: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            this.controller.buscar(this.toActivoFromSearch());
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

//    public void limpiarErrores(){
//        this.label_Comprobante.setForeground(Application.COLOR_OK);
//    }
    
//    public void fromActivo(Activo filtro){
//        if(this.box_clasificacion.getSelectedItem() == "Código")
//            text_Busca.setText(filtro.getCodigo());
//        
//    }
//    
    Activo toActivoFromSearch(){
        Activo result = new Activo();
        if(this.box_clasificacion.getSelectedItem() == "Código")
            result.setCodigo(this.text_Busca.getText());
        if(this.box_clasificacion.getSelectedItem() == "Categoría")
            result.getBien().getCategoria().setTipo(this.text_Busca.getText());
        if(this.box_clasificacion.getSelectedItem() == "Descripción")
            result.getBien().setDescripcion(this.text_Busca.getText());
        if(this.box_clasificacion.getSelectedItem() == "Dependencia")
            result.getLabor().getDependencia().setNombre(this.text_Busca.getText());
        if(this.box_clasificacion.getSelectedItem() == "Responsable")
            result.getLabor().getFuncionario().setNombre(this.text_Busca.getText());
        return result;
    }
   
    public void toSolicitudFromActivo() throws Exception {
        //Labor labor = proyecto2.logic.ModelGeneral.instance().searchLabor(Application.LOGIN_CONTROLLER.getLoginModel().getCurrent().getFuncionario().getId());
        try{
        this.controller.buscarFromActivo();
        } catch(Exception ex){ }
    }
    
    @Override
    public void update(Observable o, Object arg) {
        //this.limpiarErrores();
        //Activo filtro = model.getFilter();
        //this.fromActivo(filtro);
        table_Activo.setModel(model.getActivos());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_clasificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Activo;
    private javax.swing.JTextField text_Busca;
    // End of variables declaration//GEN-END:variables
}
