/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.rrhh.labor;

import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import proyecto2.Application;
import proyecto2.logic.Funcionario;
import proyecto2.logic.Puesto;

/**
 *
 * @author Dani
 */
public class LaborView extends javax.swing.JInternalFrame implements java.util.Observer {

    LaborController controller;
    LaborModel model;
    public LaborView() throws Exception {
        super("", false, true);
        initComponents();
    }

    public LaborController getController() {
        return controller;
    }

    public void setController(LaborController controller) {
        this.controller = controller;
    }

    public LaborModel getModel() {
        return model;
    }

    public void setModel(LaborModel model) {
        this.model = model;
        model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        funcionariosTab = new javax.swing.JTable();
        IDlabl = new javax.swing.JLabel();
        idTxtField = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        puesto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        funcionariosTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        funcionariosTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariosTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(funcionariosTab);

        IDlabl.setText("ID");

        buscar.setText("buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Funcionario a Dependencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDlabl)
                        .addGap(18, 18, 18)
                        .addComponent(idTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDlabl)
                            .addComponent(idTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
                controller.buscar(this.toFuncionario());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
    }//GEN-LAST:event_buscarActionPerformed

    private void funcionariosTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosTabMouseClicked
        if (evt.getClickCount() == 2) {
            int row = this.funcionariosTab.getSelectedRow();
            int col = this.funcionariosTab.getSelectedColumn();
            controller.editar(row, evt.getLocationOnScreen());
        }
    }//GEN-LAST:event_funcionariosTabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = funcionariosTab.getSelectedRow();
        try {
            controller.agregaLabor(row,(Puesto)puesto.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(LaborView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlabl;
    private javax.swing.JButton buscar;
    private javax.swing.JTable funcionariosTab;
    private javax.swing.JTextField idTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox puesto;
    // End of variables declaration//GEN-END:variables

   
    @Override
    public void update(Observable o, Object arg) {
        this.limpiarErrores();
        Funcionario filtro = model.getFilter();
        this.fromFuncionario(filtro);
        this.funcionariosTab.setModel(model.getFuncionarios());
        this.puesto.setModel(model.getPuestos());
    }
    
      boolean validar(){
        boolean error=false;
       
        this.IDlabl.setForeground(Application.COLOR_OK);
        if (this.IDlabl.getText().isEmpty()) {//***********cambiar
            this.IDlabl.setForeground(Application.COLOR_ERROR);
            error = true;
        }
        return !error;
    }

    public void fromFuncionario(Funcionario filtro) {
        this.idTxtField.setText(filtro.getId());
    }

    Funcionario toFuncionario() {
        Funcionario result = new Funcionario();
        result.setId(idTxtField.getText());
        return result;
    }
    
      public void limpiarErrores(){
       this.IDlabl.setForeground(Application.COLOR_OK); 
   }
     
     
}
